name: reports
version: 0.0.0
synopsis: Lab reports and assignments
description: Various reports on lab work and coursework, as well as homework assignments
maintainer: thymelous
license: OtherLicense
github: thymelous/ifmo
category: Education

default-extensions:
  - OverloadedStrings

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - HaTeX
  - mtl
  - split
  - containers
  - text

library:
  source-dirs: src
